#!/usr/bin/env python3

from src.answer_generation.article_embedder import ArticleEmbedder
import sys


if __name__ == "__main__":
    article = sys.argv[1]
    questions = sys.argv[2]

    article_embedder = ArticleEmbedder(article)
    for question in questions:
        print("find answer for question: {}".format(question))
        relevant_sentence = article_embedder.get_most_relevant_sentence_infersent(question)
        print("find most relevant sentece: {}".format(relevant_sentence))

