#!/usr/bin/env python3.6

# pip3 install spacy==2.1.0
# python3 -m spacy download en_core_web_lg
# pip3 install neuralcore --no-binary neuralcoref

import re
import sys
import os
import nltk
from nltk.parse import corenlp

DT_LIST = ['the', 'a', 'an', 'this', 'that', 'these', 'those', 'my', 'your', 'his', 'her', 'its', 'our', 'their', 'much', 'many', 'most', 'some', 'any', 'enough', 'all', 'both', 'half', 'either', 'neither', 'each', 'every', 'another', 'such', 'what', 'rather', 'quite']


def format_question(question):
    question = question.replace('-LRB- ', '(')
    question = question.replace(' -RRB-', ')')
    for det in DT_LIST:
        question = question.replace('the ' + det + " ", 'the ')
    question = question.replace('the The ', 'The ')
    question = re.sub(r"\s([,;:\.\?!\'])", r"\1", question)
    question = re.sub(r"\.\s*\?", "?", question)
    question = re.sub(r",\s*\?", "?", question)
    question = question[0].upper() + question[1:]
    return question


def blockPrint():
    sys.stdout = open(os.devnull, 'w')
    sys.stderr = open(os.devnull, 'w')


# Restore
def enablePrint():
    sys.stdout = sys.__stdout__
    sys.stderr = sys.__stderr__

common_replacements = {}
common_replacements['c.'] = 'circa'
common_replacements['ca.'] = 'circa'
common_replacements['Dr.'] = 'Doctor'
common_replacements['Esq.'] = 'Esquire'
common_replacements['Dr.'] = 'Doctor'
common_replacements['Esq.'] = 'Esquire'
common_replacements['Hon.'] = 'Honorable'
common_replacements['Jr.'] = 'Junior'
common_replacements['Mr.'] = 'Mister'
common_replacements['Mrs.'] = 'Mistress'
common_replacements['Ms.'] = 'Miss'
common_replacements['Messrs.'] = 'Misters'
common_replacements['Mmes.'] = 'Mistresses'
common_replacements['Msgr.'] = 'Monsignor'
common_replacements['Prof.'] = 'Professor'
common_replacements['Rev.'] = 'Reverend'
common_replacements['Rt. Hon.'] = 'Right Honorable'
common_replacements['Hon.'] = 'Honorable'
common_replacements['Sr.'] = 'Senior'
common_replacements['St.'] = 'Saint'
common_replacements['SS.'] = 'Saints'
common_replacements['Gen.'] = 'General'


# Replace common periods
def replace_common_periods(text):
    for key,rep in common_replacements.items():
        text = text.replace(key, rep)
    return text

# Remove dashes
def sanitize_line(line):
    pattern0 = re.compile(r'\s+')           # remove unnecessary whitespace
    pattern1 = re.compile(r'([^ ])- ')      # remove trailing -
    pattern2 = re.compile(r' -([^ ])')      # remove trailing -
    pattern3 = re.compile(r'(\s*)\.\.\.')   # remove ellipsis
    return replace_common_periods(pattern0.sub(' ', pattern1.sub(r'\1 ', pattern2.sub(r' \1', pattern3.sub('', line)))))

if __name__ == "__main__":
    article = sys.argv[1]
    nquestions = int(sys.argv[2])
    # blockPrint()
    print("Hello")
    from src.question_generation.question_gen import *
    from src.question_generation.question_gen_preprocess import preprocess
    print("Hello")

    parser = corenlp.CoreNLPParser(url='http://localhost:9000', tagtype='pos')

    parsed_list = []
    with open(article) as f:
        line = f.readline()
        while line:
            if len(line.split()) > 0:  # check for empty line

                parsed_iter = parser.parse_text(sanitize_line(line),
                                                timeout=5000)  # native output is a listiterator over detected sentences

                while True:
                    try:
                        next_item = next(parsed_iter)
                        parsed_list.append(next_item)
                    except StopIteration:
                        break
            line = f.readline()
        f.close()
    print("Hello")

    preprocessed_list, question_list = preprocess(parsed_list, parser)
    print("World")
    print(question_list)

    for parse in preprocessed_list:
        # question_list += getWhoWhat(parse) + getWhoWhatNP(parse) + getBinarySimple(parse) + getBinaryAuxiliary(parse)
        question_list += generate_questions(parse)
        pass

    i = 0
    # enablePrint()
    # while i < len(question_list) and i < nquestions:
    while i < len(question_list):
        print("Original: " + question_list[i])
        print("Formatted: " + format_question(question_list[i]) + "\n")
        i += 1
    print(len(question_list))
